In [6]:
import pandas as pd

customers = pd.read_csv("../data/raw/customers.csv")
products = pd.read_csv("../data/raw/products.csv")
orders = pd.read_csv("../data/raw/orders.csv")

print("Customers:", customers.shape)
print("Products:", products.shape)
print("Orders:", orders.shape)

Customers: (10, 7)
Products: (10, 5)
Orders: (15, 7)

In [7]:
customers.head()

,customer_id,first_name,last_name,email,country,city,signup_date
0,C001,John,Smith,john.smith@email.com,France,Paris,2025-01-15
1,C002,Emma,Johnson,emma.johnson@email.com,Germany,Berlin,2025-02-20
2,C003,Michael,Brown,michael.brown@email.com,France,Lyon,2025-03-10
3,C004,Sophia,Davis,sophia.davis@email.com,Spain,Madrid,2025-03-25
4,C005,Daniel,Wilson,daniel.wilson@email.com,Italy,Rome,2025-04-05

In [8]:
products.head()

  product_id  product_name     category  price  cost
0       P001        Laptop  Electronics   1200   850
1       P002    Smartphone  Electronics    800   550
2       P003    Headphones  Electronics    150    80
3       P004  Office Chair    Furniture    250   150
4       P005          Desk    Furniture    400   250

In [9]:
orders.head()

,order_id,customer_id,product_id,order_date,quantity,payment_method,order_status
0,O001,C001,P001,2025-06-15,1,Credit Card,Completed
1,O002,C002,P003,2025-06-16,2,PayPal,Completed
2,O003,C003,P002,2025-06-17,1,Credit Card,Completed
3,O004,C004,P005,2025-06-18,1,Bank Transfer,Completed
4,O005,C005,P006,2025-06-19,3,PayPal,Completed

In [10]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  10 non-null     object
 1   first_name   10 non-null     object
 2   last_name    10 non-null     object
 3   email        10 non-null     object
 4   country      10 non-null     object
 5   city         10 non-null     object
 6   signup_date  10 non-null     object
dtypes: object(7)
memory usage: 688.0+ bytes

In [11]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    10 non-null     object
 1   product_name  10 non-null     object
 2   category      10 non-null     object
 3   price         10 non-null     int64
 4   cost          10 non-null     int64
dtypes: int64(2), object(3)
memory usage: 528.0+ bytes

In [12]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        15 non-null     object
 1   customer_id     15 non-null     object
 2   product_id      15 non-null     object
 3   order_date      15 non-null     object
 4   quantity        15 non-null     int64
 5   payment_method  15 non-null     object
 6   order_status    15 non-null     object
dtypes: int64(1), object(6)
memory usage: 968.0+ bytes

In [13]:
print("Customers missing values:")
print(customers.isnull().sum())

print("\nProducts missing values:")
print(products.isnull().sum())

print("\nOrders missing values:")
print(orders.isnull().sum())

Customers missing values:
customer_id    0
first_name     0
last_name      0
email          0
country        0
city           0
signup_date    0
dtype: int64

Products missing values:
product_id      0
product_name    0
category        0
price           0
cost            0
dtype: int64

Orders missing values:
order_id          0
customer_id       0
product_id        0
order_date        0
quantity          0
payment_method    0
order_status      0
dtype: int64

In [14]:
print("Customer duplicates:", customers.duplicated().sum())
print("Product duplicates:", products.duplicated().sum())
print("Order duplicates:", orders.duplicated().sum())

Customer duplicates: 0
Product duplicates: 0
Order duplicates: 0

In [15]:
customers["signup_date"] = pd.to_datetime(customers["signup_date"])
orders["order_date"] = pd.to_datetime(orders["order_date"])

In [16]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  10 non-null     object
 1   first_name   10 non-null     object
 2   last_name    10 non-null     object
 3   email        10 non-null     object
 4   country      10 non-null     object
 5   city         10 non-null     object
 6   signup_date  10 non-null     datetime64[ns]
dtypes: datetime64[ns](1), object(6)
memory usage: 688.0+ bytes

In [17]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        15 non-null     object
 1   customer_id     15 non-null     object
 2   product_id      15 non-null     object
 3   order_date      15 non-null     datetime64[ns]
 4   quantity        15 non-null     int64
 5   payment_method  15 non-null     object
 6   order_status    15 non-null     object
dtypes: datetime64[ns](1), int64(1), object(5)
memory usage: 968.0+ bytes

In [18]:
print(products[["price", "cost"]].dtypes)
print(orders[["quantity"]].dtypes)

price    int64
cost     int64
dtype: object
quantity    int64
dtype: object

In [19]:
print("Invalid product prices:", (products["price"] <= 0).sum())
print("Invalid product costs:", (products["cost"] <= 0).sum())
print("Invalid order quantities:", (orders["quantity"] <= 0).sum())

Invalid product prices: 0
Invalid product costs: 0
Invalid order quantities: 0

In [20]:
orders["order_status"].value_counts()

order_status
Completed    14
Cancelled     1
Name: count, dtype: int64

In [21]:
orders["payment_method"].value_counts()

payment_method
Credit Card      8
PayPal           5
Bank Transfer    2
Name: count, dtype: int64

In [22]:
import os

# Create processed data folder if it doesn't exist
os.makedirs("../data/processed", exist_ok=True)

# Save cleaned datasets
customers.to_csv("../data/processed/customers_cleaned.csv", index=False)
products.to_csv("../data/processed/products_cleaned.csv", index=False)
orders.to_csv("../data/processed/orders_cleaned.csv", index=False)

print("Cleaned datasets saved successfully!")

Cleaned datasets saved successfully!

In [23]:
print("Duplicate customer IDs:", customers["customer_id"].duplicated().sum())
print("Missing customer IDs:", customers["customer_id"].isna().sum())

Duplicate customer IDs: 0
Missing customer IDs: 0

In [24]:
print("Duplicate product IDs:", products["product_id"].duplicated().sum())
print("Missing product IDs:", products["product_id"].isna().sum())

Duplicate product IDs: 0
Missing product IDs: 0

In [25]:
print("Duplicate order IDs:", orders["order_id"].duplicated().sum())
print("Missing order IDs:", orders["order_id"].isna().sum())

Duplicate order IDs: 0
Missing order IDs: 0

In [26]:
invalid_customers = orders[
    ~orders["customer_id"].isin(customers["customer_id"])
]

print("Invalid customer references:", len(invalid_customers))

Invalid customer references: 0

In [27]:
invalid_products = orders[
    ~orders["product_id"].isin(products["product_id"])
]

print("Invalid product references:", len(invalid_products))

Invalid product references: 0

In [28]:
print("Invalid order dates:", orders["order_date"].isna().sum())
print("Invalid signup dates:", customers["signup_date"].isna().sum())

Invalid order dates: 0
Invalid signup dates: 0

In [29]:
print("========== DATA VALIDATION SUMMARY ==========")

print("Customers:", len(customers))
print("Products:", len(products))
print("Orders:", len(orders))

print("Duplicate customer IDs:", customers["customer_id"].duplicated().sum())
print("Duplicate product IDs:", products["product_id"].duplicated().sum())
print("Duplicate order IDs:", orders["order_id"].duplicated().sum())

print("Invalid customer references:", len(invalid_customers))
print("Invalid product references:", len(invalid_products))

print("=============================================")

========== DATA VALIDATION SUMMARY ==========
Customers: 10
Products: 10
Orders: 15
Duplicate customer IDs: 0
Duplicate product IDs: 0
Duplicate order IDs: 0
Invalid customer references: 0
Invalid product references: 0
=============================================